name: Auto Assign to Project

on:
  issues:
    types: [opened, labeled]
  pull_request:
    types: [opened, labeled]

permissions:
  issues: read
  pull-requests: read
  repository-projects: write

env:
  MY_GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    environment: Action env
    steps:
    - name: Assign NEW issues and NEW pull requests to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/orgs/mlabs-haskell/projects/37'

